################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_n.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/arg_min_max.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/assign_variable.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_args.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_to.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/call_once.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/cast.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/ceil.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/comparisons.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/concatenation.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/conv_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/cumsum.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/depth_to_space.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/div.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/elementwise.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/elu.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/ethosu.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/exp.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/expand_dims.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/fill.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_div.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_mod.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather_nd.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/if.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_runner.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_util.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2norm.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/log_softmax.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/lstm_eval.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/mirror_pad.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/mul_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/neg.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/pack.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/pad.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/pooling_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/read_variable.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/reshape.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/round.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/select.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/shape.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/slice.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/softmax_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_depth.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/split.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/split_v.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/squared_difference.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/squeeze.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/strided_slice.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/svdf_common.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/tanh.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose_conv.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/unpack.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/var_handle.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/while.cc \
../Middlewares/tensorflow/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_n.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/arg_min_max.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/assign_variable.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_args.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_to.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/call_once.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cast.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ceil.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/comparisons.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/concatenation.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/conv_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cumsum.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depth_to_space.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/div.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elementwise.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elu.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ethosu.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/exp.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/expand_dims.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fill.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_div.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_mod.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather_nd.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/if.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_runner.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_util.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2norm.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/log_softmax.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/lstm_eval.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mirror_pad.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mul_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/neg.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pack.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pad.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pooling_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/read_variable.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reshape.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/round.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/select.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/shape.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/slice.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/softmax_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_depth.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split_v.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squared_difference.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squeeze.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/strided_slice.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/svdf_common.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/tanh.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose_conv.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unpack.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/var_handle.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/while.d \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_n.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/arg_min_max.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/assign_variable.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_args.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_to.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/call_once.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cast.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ceil.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/comparisons.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/concatenation.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/conv_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cumsum.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depth_to_space.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/div.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elementwise.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elu.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ethosu.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/exp.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/expand_dims.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fill.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_div.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_mod.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather_nd.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/if.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_runner.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_util.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2norm.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/log_softmax.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/lstm_eval.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mirror_pad.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mul_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/neg.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pack.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pad.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pooling_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/read_variable.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reshape.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/round.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/select.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/shape.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/slice.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/softmax_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_depth.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split_v.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squared_difference.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squeeze.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/strided_slice.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/svdf_common.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/tanh.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose_conv.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unpack.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/var_handle.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/while.o \
./Middlewares/tensorflow/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/tensorflow/tensorflow/lite/micro/kernels/%.o Middlewares/tensorflow/tensorflow/lite/micro/kernels/%.su: ../Middlewares/tensorflow/tensorflow/lite/micro/kernels/%.cc Middlewares/tensorflow/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L562xx -DTFLM_RUNTIME -DCMSIS_NN -DTFLM_RUNTIME_USE_ALL_OPERATORS=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -DTF_LITE_MCU_DEBUG_LOG -DARM_MATH -DARM_MATH_LOOPUNROLL -DARM_MATH_DSP -DARM_MATH_CM33 -D__FPU_PRESENT=1U -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../X-CUBE-AI/App -I../X-CUBE-AI -I../X-CUBE-AI/Target -I../Middlewares/tensorflow -I../Middlewares/tensorflow/third_party/flatbuffers/include -I../Middlewares/tensorflow/third_party/cmsis_nn -I../Middlewares/tensorflow/third_party/cmsis_nn/Include -I../Middlewares/tensorflow/third_party/cmsis/CMSIS/Core -I../Middlewares/tensorflow/third_party/gemmlowp -I../Middlewares/tensorflow/third_party/ruy -I../Middlewares/tensorflow/third_party/cmsis/CMSIS/Core/Include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-tensorflow-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-Middlewares-2f-tensorflow-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/activations_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_n.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_n.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/add_n.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/arg_min_max.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/arg_min_max.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/arg_min_max.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/assign_variable.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/assign_variable.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/assign_variable.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_args.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_args.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_args.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_to.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_to.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/broadcast_to.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/call_once.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/call_once.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/call_once.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cast.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cast.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cast.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ceil.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ceil.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ceil.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/comparisons.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/comparisons.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/comparisons.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/concatenation.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/concatenation.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/concatenation.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/conv_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/conv_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/conv_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cumsum.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cumsum.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/cumsum.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depth_to_space.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depth_to_space.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depth_to_space.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/dequantize_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/div.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/div.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/div.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elementwise.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elementwise.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elementwise.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elu.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elu.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/elu.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ethosu.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ethosu.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/ethosu.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/exp.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/exp.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/exp.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/expand_dims.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/expand_dims.o
	-$(RM) ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/expand_dims.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fill.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fill.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fill.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_div.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_div.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_div.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_mod.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_mod.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/floor_mod.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather_nd.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather_nd.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/gather_nd.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/if.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/if.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/if.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_runner.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_runner.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_runner.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_util.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_util.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/kernel_util.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2norm.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2norm.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/l2norm.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/log_softmax.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/log_softmax.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/log_softmax.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logical_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/logistic_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/lstm_eval.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/lstm_eval.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/lstm_eval.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mirror_pad.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mirror_pad.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mirror_pad.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mul_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mul_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/mul_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/neg.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/neg.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/neg.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pack.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pack.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pack.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pad.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pad.o
	-$(RM) ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pad.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pooling_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pooling_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/pooling_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/prelu_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/quantize_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/read_variable.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/read_variable.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/read_variable.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reduce_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reshape.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reshape.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/reshape.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/round.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/round.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/round.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/select.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/select.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/select.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/shape.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/shape.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/shape.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/slice.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/slice.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/slice.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/softmax_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/softmax_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/softmax_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_depth.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_depth.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/space_to_depth.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split_v.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split_v.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/split_v.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squared_difference.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squared_difference.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squared_difference.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squeeze.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squeeze.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/squeeze.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/strided_slice.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/strided_slice.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/strided_slice.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/sub_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/svdf_common.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/svdf_common.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/svdf_common.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/tanh.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/tanh.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/tanh.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose_conv.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose_conv.o
	-$(RM) ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/transpose_conv.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unpack.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unpack.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/unpack.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/var_handle.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/var_handle.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/var_handle.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/while.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/while.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/while.su ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/zeros_like.d ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/zeros_like.o ./Middlewares/tensorflow/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-Middlewares-2f-tensorflow-2f-tensorflow-2f-lite-2f-micro-2f-kernels

